#!/bin/sh

# Run clang-format
clang-format src/*.c src/*.h -style=file:.clang-format --dry-run -Werror
if [ $? -ne 0 ]; then
  echo "Error: Code should be formatted with clang-format."
  exit 1
fi

# Run tests
make clean
make -j$(nproc) debug=vm
make test
if [ $? -ne 0 ]; then
  echo "Tests failed."
  exit 1
fi

echo "All checks passed. Proceeding with the commit."
exit 0
